### ISSUE TITLE
FontSize has to be multiples of stepGranularity

### ISSUE THREAD

**Issue by afnx** [leisim/auto_size_text#22]
I've had this error after I upgraded the package to 2.0.0+2. Also, I've never changed my code. This one used to work in the previous version:

**Code sample**
```dart 
AutoSizeText(
     "Here is a long text.",
     textAlign: TextAlign.center,
     minFontSize: 16.0,
     maxLines: 4, 
     overflow: TextOverflow.ellipsis,
),
```
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LayoutBuilder:
flutter: FontSize has to be multiples of stepGranularity.
flutter: 'package:auto_size_text/src/auto_size_text.dart': Failed assertion: line 296 pos 14: 'style.fontSize
flutter: / widget.stepGranularity % 1 == 0'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _AutoSizeTextState._sanityCheck (package:auto_size_text/src/auto_size_text.dart:296:14)
flutter: #3      _AutoSizeTextState.build.<anonymous closure> (package:auto_size_text/src/auto_size_text.dart:253:7)
flutter: #4      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:113:26)
flutter: #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
flutter: #6      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
flutter: #7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
flutter: #8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
flutter: #9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
flutter: #10     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #14     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #18     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #20     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #22     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
flutter: #23     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:431:7)
flutter: #24     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
flutter: #25     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
flutter: #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #38     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #51     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3015:13)
flutter: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #53     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #55     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
flutter: #65     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
flutter: #66     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
flutter: #67     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
flutter: #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
flutter: #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #82     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #83     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Version**
 - Flutter version: 1.5.4
 - auto_size_text version: 2.0.0+2

**Comment by leisim** [comment]
Could you please try setting the `style` manually to something like `TextStyle(fontSize:20)`?

Either there is a problem with the library or your `AutoSizeText` inherits a fractional `fontSize`.

**Comment by afnx** [comment]
@leisim, Thank you for your answer. As far as i understand, my widget inherits the `fontSize` from my theme which defines it as 12.5. So, you're right. This fractional value causes the error. When I replace it with 12.0, it works well. However, this isn't exactly what I want. I automatically generate fractional values according to the screen, widget size etc. Is there way to pass fractional values randomly?

**Comment by leisim** [comment]
If you want to use fractional font sizes, you have to set `stepGranularity` accordingly.

For example if you want to use font sizes like `12.5`, `13`, `13.5` etc. set `stepGranularity` to `0.5`.

For `12.1`, `12.2` etc. set `stepGranularity` to `0.1`.

Unfortunately it is currently not possible to use arbitrary fractions. If you need this, please explain the reason, maybe we can find a solution.

**Comment by mono0926** [comment]
@leisim 

[textScaleFactor](https://api.flutter.dev/flutter/widgets/MediaQueryData/textScaleFactor.html) changes fontSize and it follows user settings automatically(at least on iOS).
So, if font size is 15 and textScaleFactor is [16/17](https://github.com/flutter/engine/blob/e3b8b6120eacbe16268477b9e03202969c536b59/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L882-L883), calculated font size will be 14.117647059.

I loved this package but after upgraded 2.0, I'm trouble with this restriction.

**Comment by leisim** [comment]
@mono0926
I didn't know that. I'll find a way to make it work...

**Comment by leisim** [comment]
Version `2.0.1` allows fractional font sizes again.

**Comment by ManojMMWWIndia** [comment]
I can reproduce this again with latest version.

**Comment by kjawadDeveloper1** [comment]
Any update on it

**Comment by sanchez-gonzalo94** [comment]
Same here, v3.0.0 does not work with flutter_screenutil: ^5.9.3.
